### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by krasnomovets** [sapran/dontclickshit#2]
Абзац - https://github.com/sapran/dontclickshit#windows-2
Текст: Інструкція **Micrsoft.** //Не вистачає 'o'

По всьому тексту.
Текст: авто**-**оновлення. 
Виправлення: **автооновлення**. 

Абзац - https://github.com/sapran/dontclickshit#Мобільна-безпека
Текст: Судячи з усього, _мобільна безпека Apple та безпека їхньої екосистеми застосунків_ є набагато _безпечнішою_ за рішення на базі ОС Android

Виправлення: мобільна ОС(?) Apple та їхня екосистема застосунків є набагато безпечнішої за рішення на базі ОС Android

Абзац - https://github.com/sapran/dontclickshit#Фізична-безпека
Текст: Якщо ви відвідуєте **І**нтернет-крамниці з ПК в комп'ютерному клубі або **І**нтернет-кафе – вас зламають.
Виправлення: інтернет-крамниці, інтернет-кафе.

**Comment by sapran** [comment]
Дякую!

Третє не змінюю, тому що там питання трохи ширше ніж лише ОС та додатки. Мова скоріше про монолітність харда, софта та базових сервісів від Apple.
