### ISSUE TITLE
LastPass

### ISSUE THREAD

**Issue by dmytro-gokun** [sapran/dontclickshit#8]
Є якісь об'єктивні підстави чому LastPass не включено до списку "надійних парольних менеджерів"? Як я розумію він набагато популярніший того ж dashlane. То чому його не включити до списку?

**Comment by sapran** [comment]
Наприклад, через кілька серйозних інцидентів безпеки протягом його історії. А також через обмеження безплатної версії, які нещодавно вступили в силу.

**Comment by dmytro-gokun** [comment]
> Наприклад, через кілька серйозних інцидентів безпеки протягом його історії.

Окей, інцеденти були. Тільки в них? Через ці інцеденти є доведені випадки компроментації даних користувачів? Мені здається там шлось про потенційні ризики і компанія вела себе абсолютно прозоро (що, погодьтеся, найважливіше. Може і в конкурентів випадки були, але ми про них не знаємо?). На даний момент це цілком безпечний і надійний сервіс. А як буде в майбутньому - ніхто не знає ні про LastPass ні про інші сервіси. Це, звичайно IMHO і я можу просто не володіти всією інформацією.

> А також через обмеження безплатної версії, які нещодавно вступили в силу.

Навіть з цими обмеженнями, його ціна менша ніж в 1Password, особливо якщо юзати сімейні аккаунти. До речі, 1Password має хоч близько зпівставиму безплатну версію?

NB. Я не маю ніякої афіліації з LastPass. Просто мені здається, що 1Password цілеспрямовано провадить bad PR кампанію проти нього. Через того ж Троя Ханта (я так думаю, небезкоштовно) та через численні упереджені публікації в пресі. Знову ж таки - лише моя думка і враження, я можу помилятися.

**Comment by sapran** [comment]
В мене мало аргументів на користь рекомендації LastPass. Я припинив користуватися ним не без причини. Проте, я нікому не можу заборонити рекомендувати LastPass. А мене ніхто не може змусити це робити :)

**Comment by dmytro-gokun** [comment]
Окей, діло хазяйське, як то кажуть :). Просто хотілося зрозуміти об'єктивні причини. Зрозумів, що якісь є, але які точно ми не знаємо. Добре :).
